USE QuanLyQuanTraSua
DROP TABLE NhanVien
DROP TABLE TaiKhoan
DROP TABLE LichLam
DROP TABLE KhoHang
DROP TABLE VatLieu
DROP TABLE SanPham
DROP TABLE Menu
DROP TABLE HoaDon
DROP TABLE DanhSachHoaDon

--DROP TABLE BaoCao => Make it as a View
